// ESLint Configuration for Web App
import rootConfig from '../../eslint.config.mjs';

export default [
  ...rootConfig,

  // Additional ignores specific to web app
  {
    ignores: [
      '.next/**',
      'out/**',
      'public/sw.js',
      'public/workbox-*.js',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
    ],
  },

  // Browser environment for app files
  {
    files: ['app/**/*.ts', 'app/**/*.tsx', 'lib/**/*.ts', 'lib/**/*.tsx', 'components/**/*.ts', 'components/**/*.tsx', 'contexts/**/*.ts', 'contexts/**/*.tsx', 'hooks/**/*.ts', 'hooks/**/*.tsx', 'server.ts', 'middleware.ts'],
    languageOptions: {
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        prompt: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        crypto: 'readonly',
        btoa: 'readonly',
        atob: 'readonly',
        performance: 'readonly',
        caches: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
        self: 'readonly',
        indexedDB: 'readonly',
        IDBDatabase: 'readonly',
        IDBObjectStore: 'readonly',
        IDBRequest: 'readonly',
        IDBTransaction: 'readonly',
        Notification: 'readonly',
        NotificationPermission: 'readonly',
        NotificationPermissionStatus: 'readonly',
        PushManager: 'readonly',
        PushSubscription: 'readonly',
        ServiceWorker: 'readonly',
        ServiceWorkerContainer: 'readonly',
        ServiceWorkerRegistration: 'readonly',
        // React
        React: 'readonly',
        JSX: 'readonly',
        // Node globals (for Next.js server components and API routes)
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        require: 'readonly',
        global: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
      },
    },
  },

  // Test files - allow console and expect globals
  {
    files: ['tests/**/*.ts', 'tests/**/*.tsx', '**/__tests__/**/*.ts', '**/__tests__/**/*.tsx', '**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx'],
    languageOptions: {
      globals: {
        expect: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        vitest: 'readonly',
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        fetch: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        console: 'readonly',
        process: 'readonly',
        global: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
];
